# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='matrix.proto',
  package='',
  serialized_pb=b'\n\x0cmatrix.proto\"\x14\n\x03Row\x12\r\n\x05value\x18\x01 \x03(\t\"\x1c\n\x06Matrix\x12\x12\n\x04rows\x18\x01 \x03(\x0b\x32\x04.Row')




_ROW = descriptor.Descriptor(
  name='Row',
  full_name='Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Row.value', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=36,
)


_MATRIX = descriptor.Descriptor(
  name='Matrix',
  full_name='Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rows', full_name='Matrix.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=66,
)

_MATRIX.fields_by_name['rows'].message_type = _ROW
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX

Row = reflection.GeneratedProtocolMessageType('Row', (message.Message,),
    {
      'DESCRIPTOR': _ROW,
      # @@protoc_insertion_point(class_scope:Row)
    })

Matrix = reflection.GeneratedProtocolMessageType('Matrix', (message.Message,),
    {
      'DESCRIPTOR': _MATRIX,
      # @@protoc_insertion_point(class_scope:Matrix)
    })

# @@protoc_insertion_point(module_scope)
