# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='matrix.proto',
  package='',
  serialized_pb='\n\x0cmatrix.proto\"9\n\x06Matrix\x12\x19\n\x04rows\x18\x01 \x03(\x0b\x32\x0b.Matrix.Row\x1a\x14\n\x03Row\x12\r\n\x05value\x18\x01 \x03(\t')




_MATRIX_ROW = descriptor.Descriptor(
  name='Row',
  full_name='Matrix.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='Matrix.Row.value', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=73,
)

_MATRIX = descriptor.Descriptor(
  name='Matrix',
  full_name='Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rows', full_name='Matrix.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MATRIX_ROW, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=73,
)

_MATRIX_ROW.containing_type = _MATRIX;
_MATRIX.fields_by_name['rows'].message_type = _MATRIX_ROW
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX

class Matrix(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType

  class Row(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MATRIX_ROW

    # @@protoc_insertion_point(class_scope:Matrix.Row)
  DESCRIPTOR = _MATRIX

  # @@protoc_insertion_point(class_scope:Matrix)


